update like youtube project
akbarsazish/youtube-project pull request #1
Opened 2023-05-08 22:37 UTC by akbarsazish

add read me file and some changes to the project

2023-05-08 23:00 UTC, akbarsazish reviewed
Good job so far! 👏. Your Code is Awesome! 💪
Don't Worry 🙏
It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality 💯 and help you get a better job 💼.

Highlights 🎯
✔️ clean code
✔️ Descriptive README
The code is top-notch! 💯 and has a huge potential.
 you have used few commit messages in this milestone make sure to add more messages to document each step as you build

Important Notes 📝
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Required Changes ♻️
1- configure the linters
2- use css flex box and grid, no need to use bootstrap.

Thank you for your time 🙏 and call me if you need help or clarification ☎️
This is My GitHub: @akbarsazish 
This is My linkedIn.Ali Akbar Sazish
This is My Slack: Ali Akbar Sazish


🙏 please change this part as you see on the youtube .
![Capture](https://user-images.githubusercontent.com/97288972/236954840-d637a0fd-ee25-48f8-b226-16e2bd56e437.PNG)

[Optional] suggestions:
 Next time, and for future Pull Requests, please kindly add a more descriptive PR title.

2023-05-08 23:48 UTC, jmonto55 requested changes
# STATUS: REQUIRED CHANGES 🟡

Hi @akbarsazish  👋🏽, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereGIF (2)](https://user-images.githubusercontent.com/116701485/232347575-8b3b93b1-a382-4b9e-82bd-30892aad7d39.gif)

## Required Changes ♻️
_Check the comments under the review._
- [ ] Great work making your first code review 💯. However, please kindly ensure to use [Github inline comments feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) to request your changes instead of including them in the review final message. 🤓

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 23:48 UTC, jmonto55 commented on style.css
> +  height: 45px;
This is an example of how inline comments look 👇🏽

> - [ ] Good work applying styles to your profile section ✔️. However, please kindly ensure to use flexbox to position the elements. 🤓

2023-05-09 17:17 UTC, akbarsazish reviewed
Hi @akbarsazish 👋 👋
I'm @akbarsazish , Your code reviewer,

Good job so far! 🥇

There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966](https://github.com/akbarsazish/youtube-project/assets/97288972/46b294ad-4a0d-445a-a410-90b673221f65)


Highlight
✔ Used the correct Git Flow 👍
✔ Good commit message 👍
✔ No linter errors👍
---------------------------------------------------------------------------------------------------
Required Changes ♻️
 Check the comments below
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
-------------------------------------------------------------------------------------------------

2023-05-09 17:17 UTC, akbarsazish commented on index.html
>                  </div>
You have done a great job so far!👏👏
But it would be better to use css flex box in this section.

2023-05-09 17:17 UTC, akbarsazish commented on style.css
>    margin-top: -16px;
please kindly ensure to use flexbox to position the elements.

2023-05-09 17:53 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @akbarsazish👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Used the GitHub inline comments feature at least once to leave review comments.✔️
- Utilized the Review changes feature from GitHub.✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 17:53 UTC, Johnadibe commented on index.html
>                  </div>
> [OPTIONAL] Great review @akbarsazish👍 and also using emoji😎, As was not mentioned by the previous code reviewer, Please Kindly always provide an explanation or reasoning behind each requested change. This helps the student understand why the change is being suggested and can also help them improve their skills. For example, instead of simply saying "But it would be better to use CSS flexbox in this section." only, you could say "But it would be better to use CSS flexbox in this section because it creates responsive layouts that adapt to different screen sizes and devices."😊

2023-05-09 18:04 UTC, akbarsazish commented
@Johnadibe thank you for your review and recommendation. I will consider all those in the future.

2023-05-09 18:04 UTC, merged